In [1]:
import numpy as np
from mip import *
S = np.array([200000,100000,50000,50000])
D = np.array([2000,20000,49000,18000,16000,6000,4000,7000,4000,4000,6000,3000,2000,3000,1000])
C = np.array([173,121,249,366,166,187,179,259,31,55,100,126,124,10,69,
                271,169,299,416,263,285,136,213,98,131,26,134,222,107,166,
                126,247,108,221,98,174,394,253,278,207,339,270,199,240,210,
                166,256,346,463,270,121,310,380,171,175,231,257,77,132,101]).reshape(4,15)
print(C)

[[173 121 249 366 166 187 179 259  31  55 100 126 124  10  69]
 [271 169 299 416 263 285 136 213  98 131  26 134 222 107 166]
 [126 247 108 221  98 174 394 253 278 207 339 270 199 240 210]
 [166 256 346 463 270 121 310 380 171 175 231 257  77 132 101]]


In [2]:
I = S.shape[0]
J = D.shape[0]
Prob = Model(sense=MINIMIZE,solver_name=CBC)
x = [[Prob.add_var() for j in range(J)] for i in range(I)]

for j in range(J):
    Prob += xsum(x[i][j] for i in range(I)) >= D[j]
for i in range(I):
    Prob += xsum(x[i][j] for j in range(J)) <= S[i]
    
Prob.objective = xsum(C[i][j]*x[i][j] for i in range(I) for j in range(J))
Prob.max_gap = 0.001
Prob.optimize()
X = np.zeros([I,J])
for i in range(I):
    for j in range(J):
        X[i,j] = x[i][j].x
print(X)

[[    0. 20000. 17000.     0. 16000.     0.     0.     0.  4000.  4000.
      0.  3000.     0.  3000.  1000.]
 [    0.     0.     0.     0.     0.     0.  4000.  7000.     0.     0.
   6000.     0.     0.     0.     0.]
 [    0.     0. 32000. 18000.     0.     0.     0.     0.     0.     0.
      0.     0.     0.     0.     0.]
 [ 2000.     0.     0.     0.     0.  6000.     0.     0.     0.     0.
      0.     0.  2000.     0.     0.]]
